// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2509.Robot2017;


import org.usfirst.frc2509.Robot2017.commands.OpDrive;
import org.usfirst.frc2509.Robot2017.commands.ShooterRun;
import org.usfirst.frc2509.Robot2017.commands.SweeperForward;
import org.usfirst.frc2509.Robot2017.commands.SweeperReverse;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joyopopStick button which is any button on a joyopopStick.
    // You create one by telling it which joyopopStick it's on and which button
    // number it is.
    // JoyopopStick opopStick = new JoyopopStick(port);
    // Button button = new JoyopopStickButton(opopStick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());
	
    public Joystick opStick;
    public JoystickButton ReverseSweep;
    public JoystickButton Shoot;
    
    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        opStick = new Joystick(0);
        
        // SmartDashboard Buttons
        SmartDashboard.putData("OpDrive", new OpDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        ReverseSweep = new JoystickButton(opStick, 3);
        ReverseSweep.whileHeld(new SweeperReverse());
        SmartDashboard.putData("ReverseSweep", new SweeperReverse());
        SmartDashboard.putData("Forward Sweep", new SweeperForward());
        Shoot = new JoystickButton(opStick, 1);
        Shoot.whileHeld(new ShooterRun());
        SmartDashboard.putData("Shooter Start", new ShooterRun());
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getOpStick() {
        return opStick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public double getScaledX(){
		return (opStick.getX()*((opStick.getRawAxis(3)+1.5)*0.4));
	}
	public double getScaledY(){
		return (opStick.getY()*((opStick.getRawAxis(3)+1.5)*0.4));
	}
	public double getScaledZ(){
		return -(opStick.getZ()*((opStick.getRawAxis(3)+1)*0.5));
	}
}

