// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2509.Robot2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;

import edu.wpi.cscore.UsbCamera;
import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.RobotDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveMotorLeftFront;
    public static CANTalon driveMotorRightFront;
    public static CANTalon driveMotorLeftRear;
    public static CANTalon driveMotorRightRear;
    public static RobotDrive driveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static UsbCamera FRONT_CAM;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveMotorLeftFront = new CANTalon(0);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 1", driveMotorLeftFront);
        
        driveMotorRightFront = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 2", driveMotorRightFront);
        
        driveMotorLeftRear = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 3", driveMotorLeftRear);
        
        driveMotorRightRear = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "CAN Talon 4", driveMotorRightRear);
        
        driveTrain = new RobotDrive(driveMotorLeftFront, driveMotorLeftRear,
              driveMotorRightFront, driveMotorRightRear);
        
        //driveTrain.setSafetyEnabled(true);
        //driveTrain.setExpiration(0.1);
        //driveTrain.setSensitivity(0.5);
        driveTrain.setMaxOutput(1.0);

        driveTrain.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrain.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        FRONT_CAM = CameraServer.getInstance().startAutomaticCapture();
    }
}
