// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2509.Robot2017.subsystems;

import org.usfirst.frc2509.Robot2017.OI;
import org.usfirst.frc2509.Robot2017.Robot;
import org.usfirst.frc2509.Robot2017.RobotMap;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon LeftFront = RobotMap.driveMotorLeftFront;
    private final CANTalon RightFront = RobotMap.driveMotorRightFront;
    private final CANTalon LeftRear = RobotMap.driveMotorLeftRear;
    private final CANTalon RightRear = RobotMap.driveMotorRightRear;
    private final RobotDrive robotDrive = RobotMap.driveTrain;
    private final OI oi = Robot.oi;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void OpDrive(){
    	robotDrive.mecanumDrive_Cartesian(oi.getScaledX(), oi.getScaledY(), oi.getScaledZ(), 0);
    }
}

