// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2509.Robot.subsystems;

import com.ctre.CANTalon;

import org.usfirst.frc2509.Robot.RobotMap;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *@author Nate Christensen
 *
 */
public class DriveTrain extends Subsystem {
    private final CANTalon LEFT_FRONT = RobotMap.DT_LEFTFRONT;
    private final CANTalon RIGHT_FRONT = RobotMap.DT_RIGHTFRONT;
    private final CANTalon LEFT_REAR = RobotMap.DT_LEFTREAR;
    private final CANTalon RIGHT_REAR = RobotMap.DT_RIGHTREAR;
    public final AnalogGyro GYRO = RobotMap.GYRO;
    private final RobotDrive DRIVETRAIN = RobotMap.DRIVETRAIN;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
    }
    
    public RobotDrive getDrive(){
    	return DRIVETRAIN;
    }
    public CANTalon getLeftFront(){
    	return LEFT_FRONT;
    }
    public CANTalon getLeftRear(){
    	return LEFT_REAR;
    }
    public CANTalon getRightFront(){
    	return RIGHT_FRONT;
    }
    public CANTalon getRightRear(){
    	return RIGHT_REAR;
    }
    public AnalogGyro getGyro(){
    	return GYRO;
    }
}

